soccer_sys_frontend_homepage:
    pattern:  /
    defaults: { _controller: SoccerSysFrontendBundle:Default:index }
    
SoccerSysFrontendBundle_fixture:
    resource: "@SoccerSysFrontendBundle/Resources/config/routing/match.yml"
    prefix:   /fixture

