parameters:
#    soccer_sys_frontend.example.class: SoccerSys\FrontendBundle\Example

services:
#    soccer_sys_frontend.example:
#        class: %soccer_sys_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
