team:
    pattern:  /
    defaults: { _controller: "SoccerSysFrontendBundle:Team:index" }

team_show:
    pattern:  /{id}/show
    defaults: { _controller: "SoccerSysFrontendBundle:Team:show" }

team_new:
    pattern:  /new
    defaults: { _controller: "SoccerSysFrontendBundle:Team:new" }

team_create:
    pattern:  /create
    defaults: { _controller: "SoccerSysFrontendBundle:Team:create" }
    requirements: { _method: post }

team_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SoccerSysFrontendBundle:Team:edit" }

team_update:
    pattern:  /{id}/update
    defaults: { _controller: "SoccerSysFrontendBundle:Team:update" }
    requirements: { _method: post|put }

team_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SoccerSysFrontendBundle:Team:delete" }
    requirements: { _method: post|delete }
