parameters:
#    soccer_sys_admin.example.class: SoccerSys\AdminBundle\Example

services:
#    soccer_sys_admin.example:
#        class: %soccer_sys_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
